{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test_add.TestClass object at 0x0000025892EF18D0>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x,\"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_add.py:16: AssertionError"}, "start": 1615647148966, "stop": 1615647148967, "uuid": "ff482d44-1b50-43e5-8dcc-6bdcbaf12669", "historyId": "ca01a7838a82d639601af60696d66f7d", "testCaseId": "897d4338299eac7c307a12a211e1d25a", "fullName": "test_add.TestClass#test_two", "labels": [{"name": "suite", "value": "test_add"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "9492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_add"}]}