{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_alluredemo.py:19: Exception"}, "start": 1615647149076, "stop": 1615647149076, "uuid": "ad8b8928-0bc0-423f-b9aa-c7a7662b6a4e", "historyId": "fb799eecaee64eb20ac70a0047ddd7ff", "testCaseId": "54327feac6bee8ccd45a88d670bf2886", "fullName": "test_alluredemo#test_broken", "labels": [{"name": "suite", "value": "test_alluredemo"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "9492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo"}]}